name: Swift

on:
  push:
    branches:
        - main
  pull_request:
    branches:
        - main

jobs:
  test:
    name: Test
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build
      run: |
        xcodebuild clean build -project "TriangleApp.xcodeproj" -scheme "TriangleApp" -destination "platform=iOS Simulator,name=iPhone 13,OS=15.0" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
      
    - name: Run tests
      run: |
        xcodebuild clean test -project "TriangleApp.xcodeproj" -scheme "TriangleApp" -destination "platform=iOS Simulator,name=iPhone 13,OS=15.0" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
